[server]
# This stops the inotify limit error on cloud servers
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

