[server]
# This stops the inotify limit error on cloud servers
fileWatcherType = "none"
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
